---
title: "MR BMI"
author: "Li-Fang Yeo"
date: "2025-01-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
library(readr)
```
```{r}
#Hello! Where did you come from?? Kuka sä oot??
BMI_IRN <- read_delim("BMI_IRN.tsv", delim = "\t", 
+     escape_double = FALSE, trim_ws = TRUE)
```
```{r}
#read sscore from plink2 for PCA

chr1and2_projected <- read_delim("chr1and2_projected.sscore", 
     delim = "\t", escape_double = FALSE, 
     trim_ws = TRUE)

chr1_25_projected <- read_delim("chr1.25_projected.sscore", 
+     delim = "\t", escape_double = FALSE, 
+     trim_ws = TRUE)
```
```{r}
#merge
b <- tibble::rownames_to_column(b, "ID")
#Problem = PCA will change because some samples are missing?
hi <- chr1and2_projected %>% dplyr::right_join(b, join_by(IID == ID))

##This plot is chr1 and chr2 and samples filtered to n=5846
ggplot(hi, aes(x=PC1_AVG, y=PC2_AVG)) + 
         geom_point()
```
```{r}
#This plot is chr1 and chr2, n=7362
ggplot(chr1and2_projected, aes(x=PC1_AVG, y=PC2_AVG)) + 
         geom_point()
```
```{r}
ggplot(chr1_25_projected, aes(x=PC1_AVG, y=PC2_AVG)) + 
         geom_point()
```

